### ISSUE TITLE
도커환경내 디버그 이슈 리포트

### ISSUE THREAD

**Issue by Zamoca42** [pre-onboarding-backend-G/get-your-feeds#11]
##  이슈 내용

- 도커 환경에서 디버깅하고 IDE내에서 도커환경을 설정하고 개발을 이어나갈 수 있도록 DevContainer 설정

<br>

##  작업 사항
- [x] .devcontainer 설정
- [x] .vscode/launch.json (디버그) 설정
- [x] local.dockerfile 설정 변경
- [x] docker-compose.yml에 NestJS 디버그 포트 추가

<br>

## 기타사항

DevContainer란 무엇인가?

>https://ssowonny.medium.com/vs-code%EB%A1%9C-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EC%95%88%EC%97%90%EC%84%9C-%EA%B0%9C%EB%B0%9C%ED%95%98%EA%B8%B0-d8ed0950d69a

>https://code.visualstudio.com/docs/devcontainers/containers

DevContainer는 주로 Visual Studio Code와 같은 통합 개발 환경(IDE)에서 사용되며, Visual Studio Code의 Remote Development 확장 프로그램을 통해 손쉽게 구성할 수 있습니다. 이를 통해 프로젝트를 개발하는 동안 개발 환경을 컨테이너 내에서 실행하고 호스트 시스템과 분리시키는 것이 가능합니다.

DevContainer를 설정하려면 프로젝트 루트 디렉토리에 .devcontainer 디렉토리를 만들고, 그 안에 Dockerfile 및 환경 설정 파일을 구성해야 합니다. 그런 다음 Visual Studio Code와 같은 지원하는 IDE에서 프로젝트를 열면 DevContainer를 자동으로 시작하고 개발 환경을 설정할 수 있습니다.

왜 DevContainer 인가?
    - OS마다 개발환경이 적용이 안되는 상황이 발생했습니다.
    - `docker compose up` 명령으로 실행 시 디버깅을 할 수 있는 방법이 없었습니다.
 -> IDE(VScode)내에서 도커를 사용하고 개발 환경을 적용해보자.

> https://code.visualstudio.com/docs/devcontainers/create-dev-container

### 1. DevContainer 확장앱 설치

<img width="1635" alt="스크린샷 2023-10-27 오후 10 16 17" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/ae2eda57-d2d0-48de-8b68-107bcdf56dac">

### 2. `F1`을 누르고 vscode의 명령팔레트에서 '개발 컨테이너 구성파일 추가'를 시작합니다.

<img width="1273" alt="스크린샷 2023-10-27 오후 10 47 40" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/44bdf82f-3ae5-41d4-8b50-e05d7e5f47c1">

설정에서 이미 작동중인 docker-compose.yml을 가져오거나 새로 설정해줄 수 있습니다.

**.devcontainer/devcontainer.json**
```json
{
	"name": "Existing Docker Compose (Extend)",

	// Update the 'dockerComposeFile' list if you have more compose files or use different names.
	// The .devcontainer/docker-compose.yml file contains any overrides you need/want to make.
	"dockerComposeFile": [
		"../docker-compose.yml",
		"docker-compose.yml"
	],
}
```

**.devcontainer/docker-compose.yml**

```yaml
version: '3.9'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  nest-app:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
```

### 3. 설정파일이 생성되었다면 다시 `F1`을 누르고 명령 팔레트로 들어가서 '컨테이너에서 다시 빌드하고 다시 열기'를 선택합니다.

<img width="1273" alt="스크린샷 2023-10-27 오후 10 50 27" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/c3f367d1-c57b-48ea-86d6-5e8f97324201">

### 4. 빌드가 끝나면 리눅스 환경처럼 터미널을 쓸 수 있는 NestJS를 vscode 내에서 사용할 수 있습니다.

<img width="468" alt="스크린샷 2023-10-27 오후 9 45 23" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/ded96dde-87c6-4fc8-acb7-14a4c8ebe88d">

### 5. `.vscode/launch.json`에서 디버깅 설정파일을 만들고 설정합니다.

```json
{
  // IntelliSense를 사용하여 가능한 특성에 대해 알아보세요.
  // 기존 특성에 대한 설명을 보려면 가리킵니다.
  // 자세한 내용을 보려면 https://go.microsoft.com/fwlink/?linkid=830387을(를) 방문하세요.
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "디버그: 프로그램 시작",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "port": 9229,
      "restart": true
    }
  ]
}
```

### 6. `npm run start:debug`를 터미널에서 실행하면 실행 및 디버그에서 디버그를 시작할 수 있습니다.

<img width="1273" alt="스크린샷 2023-10-27 오후 11 01 43" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/daf04a35-2c26-4a28-8038-ace4678f1659">

<img width="1273" alt="스크린샷 2023-10-27 오후 11 02 23" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/be14badb-d26b-4375-8e91-dda5cd0fe911">

### 7. 브레이크 포인트를 찍고 디버깅이 가능해집니다.

<img width="650" alt="스크린샷 2023-10-27 오후 9 37 58" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/07776db5-4fcd-441e-9d29-f32c7b2bff01">

<img width="530" alt="스크린샷 2023-10-27 오후 9 37 24" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/90be6d12-fc3e-41eb-9fa3-a2c570b6994b">

<img width="530" alt="스크린샷 2023-10-27 오후 9 37 16" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/23479a6e-b264-47c3-b06f-29fe8af52a1f">

<img width="530" alt="스크린샷 2023-10-27 오후 9 37 45" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/4861f92b-dadd-409a-b2c2-3c308375d5a4">

<img width="1273" alt="스크린샷 2023-10-28 오전 12 50 51" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/d7c547e8-7140-46ad-ab22-e5678486632c">

### 8. 왼쪽 아래 파란색 개발 컨테이너를 클릭하면 원격 연결을 종료할 수 있습니다.

<img width="468" alt="스크린샷 2023-10-27 오후 9 45 23" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/a001b824-5ca1-4311-b51c-2e208120a7c6">

<img width="1273" alt="스크린샷 2023-10-27 오후 10 23 04" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/478f358c-ef27-4cd2-812a-b75829a012f1">

<br>
